[package]
name = "ACTL_Query_Pro"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde_json = "1.0.128"
log = "0.4.22"
tokio = { version = "1.40.0", features = ["time"] }
csv = "1.3.0"
colored = "2.1.0"